version: '3.9'

services:
  cassandra_db_node_1_seed:
    container_name: cassandra_db_node_1_seed
    image: cassandra:4.1.3
    ports:
      - "9041:9042"
    environment:
      - CASSANDRA_SEEDS=172.16.238.11
      - CASSANDRA_CLUSTER_NAME=TutorialCluster
      - CASSANDRA_DC=dc
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1000000000
    networks:
      cassandra_network:
        ipv4_address: 172.16.238.11

  cassandra_db_node_2:
    container_name: cassandra_db_node_2
    image: cassandra:4.1.3
    ports:
     - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=172.16.238.11
      - CASSANDRA_CLUSTER_NAME=TutorialCluster
      - CASSANDRA_DC=dc
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1000000000
    networks:
      cassandra_network:
        ipv4_address: 172.16.238.12

  cassandra_db_node_3:
    container_name: cassandra_db_node_3
    image: cassandra:4.1.3
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=172.16.238.11
      - CASSANDRA_CLUSTER_NAME=TutorialCluster
      - CASSANDRA_DC=dc
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1000000000
    networks:
      cassandra_network:
        ipv4_address: 172.16.238.13

networks:
  cassandra_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24